name: Rust

env:
  CARGO_TERM_COLOR: always

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'

jobs:
  fmt:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - run: rustup component add rustfmt
    - uses: Swatinem/rust-cache@v2

    - run: cargo fmt --all -- --check

  clippy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - run: rustup component add clippy
    - uses: Swatinem/rust-cache@v2

    - run: cargo clippy --all

  doc:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - run: rustup install nightly --profile minimal
    - uses: Swatinem/rust-cache@v2

    - name: Run check
      run: ./build_doc.sh

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - run: |
        rustup toolchain install nightly --profile minimal --component rust-src --component miri
        rustup override set nightly
    - uses: Swatinem/rust-cache@v2

    - run: ./run_test.sh

  # Dummy job to have a stable name for the "all tests pass" requirement
  tests-pass:
    name: Tests pass
    needs:
    - fmt
    - clippy
    - doc
    - build
    if: always() # always run even if dependencies fail
    runs-on: ubuntu-latest
    steps:
    # fail if ANY dependency has failed or cancelled
    - if: "contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')"
      run: exit 1
    - run: exit 0
